//左侧导航数据
export const CATEGORY_LEFT_TIT_ADD_ACTION = "CATEGORY_LEFT_TIT_ADD_ACTION";
export const CATEGORY_LEFT_TIT = "CATEGORY_LEFT_TIT";
//右侧导航数据
export const CATEGORY_RIGHT_TIT_ADD_ACTION = "CATEGORY_RIGHT_TIT_ADD_ACTION";
export const CATEGORY_RIGHT_TIT = "CATEGORY_RIGHT_TIT";
/* 分类页面数据初始化 */
export const CATEGORY_INIT_DATA_ADD_ACTION = "CATEGORY_INIT_DATA_ADD_ACTION";
export const CATEGORY_INIT_DATA = "CATEGORY_INIT_DATA";

//购物车
export const CART_GET_MSG = "CART_GET_MSG";
export const CART_CHANGE_SELECT = "CART_CHANGE_SELECT";
export const CART_ALL_SELECT = "CART_ALL_SELECT";
export const CART_ADD_GOODS = "CART_ADD_GOODS";
export const CART_SUB_GOODS = "CART_SUB_GOODS";
export const CART_MANAGE_CHANGE_SELECT = "CART_MANAGE_CHANGE_SELECT";
export const CART_MANAGE_ALL_SELECT = "CART_MANAGE_ALL_SELECT";
export const CART_DEL_GOODS = "CART_DEL_GOODS";
export const CART_COUPON_MSG = "CART_COUPON_MSG";
export const CART_USE_COUPON = "CART_USE_COUPON";

export const HOME_ADD_ACTION = "HOME_ADD_ACTION";
/* 轮播图数据的初始化 action */
export const HOME_INIT_SWIPER_DATA = "HOME_INIT_SWIPER_DATA";

export const HOME_INIT_CENTER_DATA = "HOME_INIT_CENTER_DATA";

export const HOME_INIT_PURCHASE_DATA = "HOME_INIT_PURCHASE_DATA";

export const HOME_INIT_GROUPSHOP_DATA = "HOME_INIT_GROUPSHOP_DATA";

export const HOME_INIT_INFORMATION_DATA = "HOME_INIT_INFORMATION_DATA";

export const HOME_INIT_SEARCH_DATA = "HOME_INIT_SEARCH_DATA";

//my
export const MY_INIT_BALANCE = "MY_INIT_BALANCE";
export const MY_ADD_ACTION = "MY_ADD_ACTION";
export const MY_INIT_ICON = "MY_INIT_ICON";
export const MY_INIT_ICONS = "MY_INIT_ICONS";
export const MY_INIT_USER = "MY_INIT_USER";
export const MYORDER_INIT_ORDER = "MYORDER_INIT_ORDER";
